//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalEntry
    {
        public int Id { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Description { get; set; }
    
        public virtual Position Position { get; set; }
        public virtual EntryCategory EntryCategory { get; set; }
    }
}
